[package]
name = "embedded-time"
version = "0.1.0"
authors = ["Peter Taylor <ptaylor@fluentech.info>"]
edition = "2018"
keywords = ["no_std", "time", "Duration", "Instant"]
categories = ["date-and-time", "embedded", "no-std"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2.11", default-features = false }

[[example]]
name = "nrf52_dk"

[dev-dependencies]
cortex-m = "0.6.2"
cortex-m-rtfm = "0.5.1"
panic_rtt = "0.2.0"
nrf52832-hal = { version = "0.10.0", default-features = false, features = ["rt", "xxAA-package"] }
mutex-trait = "0.2.0"

[patch.crates-io]
cortex-m = { git = "https://github.com/rust-embedded/cortex-m", branch = "mutex_add" }
panic_rtt = { git = "https://github.com/PTaylor-FluenTech/jlink_rtt", branch = "master" }
