name: CI

on: [push, pull_request]

jobs:
  AllChecks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-latest, windows-latest]
        target: [thumbv7em-none-eabihf]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo--${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Build lib
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --all-features

      - name: Test Library
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --all-features -- --test-threads=1

      - name: Test Documentation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --features serde

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Doc Generation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features

      - name: Build examples
        uses: marcopolo/cargo@master
        with:
          command: build
          working-directory: examples
          args: --target ${{ matrix.target }} --release

      - name: Clippy examples
        uses: marcopolo/cargo@master
        with:
          command: clippy
          working-directory: examples
          args: --target ${{ matrix.target }}
