name: Clippy

on: {push, pull_request}

jobs:
  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest, windows-latest]
        target: [thumbv7em-none-eabihf]

    steps:
      - uses: actions/checkout@v2

      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo--${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --lib --examples --target thumbv7em-none-eabihf
          toolchain: nightly
