name: Clippy

on: {push, pull_request}

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --lib --examples --target ${{ matrix.target }}
          toolchain: nightly
